//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.28 at 03:24:37 PM IST 
//


package com.hcentive.hackathon.commons.notifier.impl.htmedia;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hCentive.commons.notifier.impl.htmedia package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hCentive.commons.notifier.impl.htmedia
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message.Submit.From }
     * 
     */
    public Message.Submit.From createMessageSubmitFrom() {
        return new Message.Submit.From();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Message.Submit.Oa }
     * 
     */
    public Message.Submit.Oa createMessageSubmitOa() {
        return new Message.Submit.Oa();
    }

    /**
     * Create an instance of {@link Message.Submit.Da }
     * 
     */
    public Message.Submit.Da createMessageSubmitDa() {
        return new Message.Submit.Da();
    }

    /**
     * Create an instance of {@link Message.Submit }
     * 
     */
    public Message.Submit createMessageSubmit() {
        return new Message.Submit();
    }

}
